### ISSUE TITLE
Mirrors *unofficial*

### ISSUE THREAD

**Issue by Munzy** [CBPP/crunchbangplusplus.org#3]
https://cdn.content-network.net/mirror/crunchbangplusplus/1.0/

I setup a mirror if you would like to add it to the site.

Enjoy.

**Comment by overlandandseas** [comment]
awesome thank you! I will check these just to verify they are good tonight, if that goes will I'll put them up. There a company or page or want to say these are from?

**Comment by Munzy** [comment]
No company that I can think of, you can point it at my forums if you so choose https://www.qwdsa.com/ or my project site https://www.enjen.net/ or just say thanks to @munroenet. 

If you have any preferred method of communication let me know, and I'll give you mine and Ill update the mirror as needed.

Later down the road I may make a nice download site and theme for it, but right now this is what you got.
